name: test download

on:
  push:
    branches:
      - main

jobs:
  test_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: create files
        run: python create-files.py
      - uses: actions/upload-artifact@v4
        with:
          name: files
          path: |
            file*
            tfile*
            gfile*

  test_download:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/download-artifacts@v4
        with:
          name: files
          path: |
            file*
      - name: display file names
        run: ls -alrt
      - name: display contents
        run: python 